### ISSUE TITLE
ModuleNotFoundError: No module named 'woodwork.serialize'

### ISSUE THREAD

**Issue by coffeeboost** [alteryx/open_source_demos#54] opened 2022-12-06 01:42 UTC
Bug report.
Steps:
- added csv to data folder in root
- created virtualenv
- installed requirements
- opened jupyter notebook
- ran ~/open_source_demos/predict-next-purchase/Tutorial.ipynb
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[28], line 6
      4 import os
      5 import composeml as cp
----> 6 import featuretools as ft
      7 import dask.dataframe as dd
      8 import numpy as np

File ~/Desktop/featuretools/lib/python3.8/site-packages/featuretools/__init__.py:4
      2 from .config_init import config
      3 from . import variable_types
----> 4 from .entityset.api import *
      5 from . import primitives
      6 from .synthesis.api import *

File ~/Desktop/featuretools/lib/python3.8/site-packages/featuretools/entityset/__init__.py:2
      1 # flake8: noqa
----> 2 from .api import *

File ~/Desktop/featuretools/lib/python3.8/site-packages/featuretools/entityset/api.py:3
      1 # flake8: noqa
      2 from .deserialize import read_entityset
----> 3 from .entityset import EntitySet
      4 from .relationship import Relationship
      5 from .timedelta import Timedelta

File ~/Desktop/featuretools/lib/python3.8/site-packages/featuretools/entityset/entityset.py:12
      9 from woodwork import init_series
     10 from woodwork.logical_types import Datetime
---> 12 from featuretools.entityset import deserialize, serialize
     13 from featuretools.entityset.relationship import Relationship, RelationshipPath
     14 from featuretools.feature_base.feature_base import _ES_REF

File ~/Desktop/featuretools/lib/python3.8/site-packages/featuretools/entityset/serialize.py:7
      4 import tarfile
      5 import tempfile
----> 7 from woodwork.serialize import typing_info_to_dict
      9 from featuretools.utils.gen_utils import import_or_none
     10 from featuretools.utils.s3_utils import get_transport_params, use_smartopen_es

ModuleNotFoundError: No module named 'woodwork.serialize'
```

**Comment by doxenix** [comment] 2023-01-16 22:11
Did you found solution?

**Comment by thehomebrewnerd** [comment] 2023-01-17 14:41
@coffeeboost @doxenix This error appears to be caused by a version incompatibility with Woodwork. I believe if you install version `0.11.2` of Woodwork in your environment with `pip install woodwork==0.11.2` this error should go away. 

I will make this update in the requirements file to prevent this error in the future.

**Comment by thehomebrewnerd** [comment] 2023-01-17 14:45
I'm closing this issue as the change in #55 should resolve this problem. If you still have problems after this update to use Woodwork `0.11.2`, feel free to reopen this issue.

**Closed by thehomebrewnerd** 2023-01-17 14:45 UTC
